Learnosity/learnosity-sdk-php

src/LearnositySdk/Request/Init.php, src/tests/LearnositySdk/Request/InitTest.php
=> [FEATURE] Add support for expire security parameter

README.md
Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>
=> [DOC] Improve doc for dataAPI->request()

src/LearnositySdk/Request/Remote.php
By default, libcurl is sending `Expect: 100-Continue` header when the
request body is above a certain size. The server MAY send a 100-Continue
header in the same stream as the final response to comply with this -
depending on the state of the request body upload.
When callers check the response object, they may see 100 as the response
status code instead of 200 in this case. This is confusing. This change
prevents it.
=> [BUG] Prevent a 100-Continue response from the server

src/LearnositySdk/Request/DataApi.php
- Add backlashes in `use` for DataApi
- give some more details about using the `Remote` object with `request`
Signed-off-by: Olivier Mehani olivier.mehani@learnosity.com
=> [CLEANUP] Minor fixes

README.md, bootstrap.php, examples/simple/init_data.php, examples/simple/init_items.php, phpunit.xml, src/tests/bootstrap.php
They are a line-by-line copy of the Ruby examples at the time of this
writing.
Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>
=> [DOC] Add simple example of signing and Data API requests

README.md, composer.json, composer.lock
This PR tests the Learnosity SDK against PHP 7 to make sure it is PHP 5 and PHP 7 compatible.
The vendor changes in composer reflects this.
=> [VENDOR] Updating phpunit to be php7 compatible

src/LearnositySdk/Utils/Json.php, src/tests/LearnositySdk/Utils/JsonTest.php
- replace all scientific values with float values
LRN-17413
=> [BUG] Signature mismatch with large floats

README.md
https://github.com/PUGX/badge-poser
Signed-off-by: Olivier Mehani <olivier.mehani@learnosity.com>
=> [DOC] Add fancy badges to readme, thanks to PUGX/badge-poser

.codeclimate.yml
=> [TEST] Add codeclimate config

ChangeLog.md, src/LearnositySdk/Request/Init.php, src/tests/LearnositySdk/Request/InitTest.php
=> [BUG] Prevent overwriting of meta field - CAT-178

README.md, src/tests/LearnositySdk/Request/InitTest.php
=> [DOCS] Clarify user_id examples CAT-77

ChangeLog.md, src/LearnositySdk/Request/Init.php, src/tests/LearnositySdk/Request/InitTest.php
=> [BUG] Fix error on null request packet CAT-240

.travis.yml, ChangeLog.md, composer.json
=> [FEATURE] PHP 7.4 upgrade CAT-437

src/LearnositySdk/Request/DataApi.php
Use array_merge_recursive to prevent results overrides
=> [BUG] Fix Data API requestRecursive

Makefile, README.md, release.sh
=> [BUG] Fix release script

release.sh
=> [BUG] Fix bug with release.sh

Makefile
=> [BUG] Fix creation of release zip

REFERENCE.md, docs/quickstart/analytics/init_data.php
=> Remove v1 versions from Data API calls and insert LTS versions

.travis.yml
=> [BUG] Removed php support 7.0 for travis CI - LRN-40620

Dockerfile, Makefile, tests/Request/InitTest.php
=> LRN-34270 [FEATURE] Containerise dev environment

ChangeLog.md, src/Request/Init.php, src/SdkFactory.php, tests/Request/InitTest.php, tests/SdkFactoryTest.php
=> [FEATURE] Generate signed requests for author aide

ChangeLog.md, src/Request/Init.php, tests/Request/InitTest.php, tests/SdkFactoryTest.php
=> [BUG] Rename author-aide to authoraide

Dockerfile, src/Services/PreHashStrings/LegacyPreHashString.php, tests/Request/InitTest.php, tests/Services/PreHashStrings/LegacyPreHashStringTest.php
=> LRN-43664 Remove newer code unavailable in all supported PHP versions

.travis.yml, composer.json
=> [CONFIG] Update PHP version to 8.3 - LRN-45449

ChangeLog.md
=> [DOC] Update changelog - LRN-45449

Makefile
=> Lrn 48024/bug/release process error
